# Generated by Django 2.0.8 on 2018-12-27 14:07

import core.custom_models_fields
import core.custom_validators
import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='2fb1cb72', editable=False, max_length=8)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=core.utils.PathAndRename(), verbose_name='file')),
                ('original_filename', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='original filename')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('_sha1', models.CharField(blank=True, default='', max_length=40, verbose_name='sha1')),
                ('_status', models.IntegerField(choices=[(0, 'undefined'), (1, 'loaded'), (2, 'cleaned'), (3, 'learned'), (4, 'predicted')], default=0, verbose_name='status')),
                ('_type', models.IntegerField(choices=[(1, 'img'), (2, 'file'), (3, 'xls'), (4, 'json'), (5, 'xml'), (6, 'csv'), (7, 'txt'), (8, 'html'), (9, 'void')], default=9, null=True, verbose_name='type')),
                ('_file_size', models.BigIntegerField(blank=True, null=True, verbose_name='file size')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('is_public', models.BooleanField(default=False, verbose_name='Permissions disabled')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorite')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_filer_file', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('perms', models.ManyToManyField(blank=True, help_text='Specific permissions by object.', related_name='filer_file_related', related_query_name='filer_files', to='account.Perm', verbose_name='object permissions')),
                ('subjects', tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_initial=True, autocomplete_view='tag_subject_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='CRM, HR, IT, business, correlation, customers, learning, legal, production, retail, retail/sales, retail/stocks', max_count=15, to='tag.TagSubject', tree=True)),
            ],
            options={
                'verbose_name': 'data file',
                'verbose_name_plural': 'data files',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='ac87a849', editable=False, max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='icon')),
                ('color', core.custom_models_fields.ColorField(default='#EEEEEE', max_length=7, validators=[core.custom_validators.validate_color], verbose_name='color')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('is_root', models.BooleanField(default=False, verbose_name='root folder')),
                ('file', models.ManyToManyField(blank=True, help_text='file in folders', related_name='filer_folder_related', related_query_name='filer_folders', to='filer.File', verbose_name='files in folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_filer_folder', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filer.Folder', verbose_name='parent folder')),
                ('perms', models.ManyToManyField(blank=True, help_text='Specific permissions by object.', related_name='filer_folder_related', related_query_name='filer_folders', to='account.Perm', verbose_name='object permissions')),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
            },
        ),
    ]
