# Generated by Django 2.0.8 on 2019-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uid',
            field=models.CharField(default='49e877f2', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.CharField(default='8c922cb5', editable=False, max_length=8),
        ),
    ]
