# Generated by Django 2.0.8 on 2019-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0002_auto_20190108_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='_status',
            field=models.IntegerField(choices=[(0, 'undefined'), (1, 'unload'), (2, 'loaded'), (3, 'cleaned'), (4, 'learned'), (5, 'predicted')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
