# Generated by Django 2.0.8 on 2019-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181227_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='6f11ba4f', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.CharField(default='f210a9e1', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='b1f18838', editable=False, max_length=8),
        ),
    ]
