# Generated by Django 2.0.8 on 2019-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190108_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='5c832643', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
