# Generated by Django 2.0.8 on 2019-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190121_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='960bac07', editable=False, max_length=8),
        ),
    ]
