# Generated by Django 2.0.8 on 2019-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190121_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='9598a38c', editable=False, max_length=8),
        ),
    ]
