# Generated by Django 2.0.8 on 2019-02-05 15:33

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190121_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='44299911', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_initial=True, autocomplete_view='tag:tag_subject_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='CRM, HR, IT, business, correlation, customers, learning, legal, production, retail, retail/sales, retail/stocks', max_count=15, to='tag.TagSubject', tree=True),
        ),
    ]
