# Generated by Django 2.0.8 on 2019-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190205_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='4af496d6', editable=False, max_length=8),
        ),
    ]
