# Generated by Django 2.0.8 on 2019-02-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190206_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='9ba81850', editable=False, max_length=8),
        ),
    ]
