# Generated by Django 2.0.8 on 2019-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190206_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='6115bc3a', editable=False, max_length=8),
        ),
    ]
