# Generated by Django 2.0.8 on 2019-02-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190208_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='82bc5274', editable=False, max_length=8),
        ),
    ]
