# Generated by Django 2.0.8 on 2019-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190208_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='145c4f25', editable=False, max_length=8),
        ),
    ]
