# Generated by Django 2.0.8 on 2019-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190208_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='cf449a80', editable=False, max_length=8),
        ),
    ]
