# Generated by Django 2.0.8 on 2019-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190208_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='f04431df', editable=False, max_length=8),
        ),
    ]
