# Generated by Django 2.0.8 on 2019-02-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190211_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='18ea379f', editable=False, max_length=8),
        ),
    ]
