# Generated by Django 2.0.8 on 2019-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190212_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='9524e82f', editable=False, max_length=8),
        ),
    ]
