# Generated by Django 2.0.8 on 2019-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20190212_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='8abf2545', editable=False, max_length=8),
        ),
    ]
