# Generated by Django 2.0.8 on 2019-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190212_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='618f63f9', editable=False, max_length=8),
        ),
    ]
