# Generated by Django 2.0.8 on 2019-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20190213_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='8342fcb8', editable=False, max_length=8),
        ),
    ]
