# Generated by Django 2.0.8 on 2019-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20190214_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='39379f05', editable=False, max_length=8),
        ),
    ]
