# Generated by Django 2.0.8 on 2019-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20190215_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='6f2a894a', editable=False, max_length=8),
        ),
    ]
