# Generated by Django 2.0.8 on 2019-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20190221_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='afa2e5bf', editable=False, max_length=8),
        ),
    ]
