# Generated by Django 2.0.8 on 2019-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20190222_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='85bbac4b', editable=False, max_length=8),
        ),
    ]
