# Generated by Django 2.0.8 on 2019-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20190328_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='7162991f', editable=False, max_length=8),
        ),
    ]
