# Generated by Django 2.0.8 on 2019-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20190329_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='e7005a77', editable=False, max_length=8),
        ),
    ]
