# Generated by Django 2.0.8 on 2019-04-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20190402_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='1553c5e6', editable=False, max_length=8),
        ),
    ]
