# Generated by Django 2.0.8 on 2019-04-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20190408_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='eae9d225', editable=False, max_length=8),
        ),
    ]
