# Generated by Django 2.0.8 on 2019-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20190428_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='uiid',
            field=models.CharField(default='51c95386', editable=False, max_length=8),
        ),
    ]
