# Generated by Django 2.0.8 on 2018-12-27 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('level', models.IntegerField(default=0, verbose_name='status')),
                ('extra_tags', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='extra tag')),
                ('message', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_to_message_message', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
