# Generated by Django 2.0.8 on 2019-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollect', '0003_column_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='clean',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='alter',
            field=models.IntegerField(choices=[(0, 'unchanged'), (1, 'intize'), (2, 'floatize'), (3, 'timize'), (4, 'splitize'), (5, 'substrize'), (6, 'regexize')], default=0, help_text='Do you need to transform this field and how would you transform it ?<br>transform string to number or time format, extract a substring or set a &quot;regex&quot; rule', verbose_name='field transformation'),
        ),
        migrations.AlterField(
            model_name='column',
            name='category',
            field=models.IntegerField(choices=[(0, 'keep'), (1, 'dummies'), (2, 'frequencies'), (3, 'ordinals')], default=0, help_text='How would you manage category velues ?<br>Category is a non numerical value that can not be computed (sum, mean,... )<br>it is often a text field like country or color...', verbose_name='managing categories'),
        ),
        migrations.AlterField(
            model_name='column',
            name='drop_column',
            field=models.BooleanField(choices=[(True, 'Drop Field'), (False, '')], default=False, help_text='drop this column ?', verbose_name='drop this column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='nan',
            field=models.IntegerField(choices=[(0, 'leave'), (1, 'drop'), (2, 'binary'), (3, 'median'), (4, 'mean'), (5, 'highfreq'), (6, 'lowfreq'), (7, 'max'), (8, 'min'), (9, 'value')], default=0, help_text='What do you want to do when values are missing ?<br>Drop rows with none values or set a rule for replacing them them.<br>e.g. use statistics indicators (median, mean, max...) in place of missing values', verbose_name='managing missing values'),
        ),
        migrations.AlterField(
            model_name='column',
            name='target',
            field=models.BooleanField(choices=[(True, 'Target Field'), (False, '')], default=False, help_text='is this column a target for prediction or classification ?', verbose_name='is a target ?'),
        ),
    ]
