# Generated by Django 2.0.8 on 2019-04-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollect', '0004_auto_20190402_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='datacollect.DataSet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='column',
            name='category',
            field=models.IntegerField(choices=[(0, 'keep'), (1, 'dummelies'), (2, 'frequencies'), (3, 'ordinals')], default=0, help_text='How would you manage category velues ?<br>Category is a non numerical value that can not be computed (sum, mean,... )<br>it is often a text field like country or color...', verbose_name='managing categories'),
        ),
        migrations.AlterField(
            model_name='column',
            name='drop_column',
            field=models.BooleanField(default=False, help_text='drop this column ?', verbose_name='drop column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='rename',
            field=models.CharField(blank=True, help_text='type a new name for the column', max_length=100, null=True, verbose_name='rename this column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='target',
            field=models.BooleanField(default=False, help_text='is this column a target for prediction or classification ?', verbose_name='set as target'),
        ),
    ]
