# Generated by Django 2.0.8 on 2019-05-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollect', '0005_auto_20190428_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_format', models.IntegerField(choices=[(13, 'yyyy-MM-ddXXX ***** 1999-03-22+01:00'), (19, "yyyy-MM-dd'T'HH:mm:ssXXX ***** 1999-03-22T05:06:07+01:00"), (15, "yyyy-MM-dd'T'HH:mm:ss.SSS ***** 1999-03-22T05:06:07.000"), (28, 'dd-MM-yyyy ***** 22-03-1999'), (16, "yyyy-MM-dd'T'HH:mm:ss ***** 1999-03-22T05:06:07"), (2, 'yyyyMMddHHmm ***** 199903222046'), (3, 'yyyyMMddhhmm ***** 199903220846'), (14, "yyyy-MM-dd'T'HH:mm:ss.SSS['VV'] ***** 1999-03-22T05:06:07.000[Europe/Paris]"), (23, "yyyy-MM-dd'T'HH:mm:ss.SSSXXX'['VV']' ***** 1999-03-22T05:06:07.000+01:00[Europe/Paris]"), (25, 'ddMMyyyy ***** 22031999'), (10, 'yyMMdd ***** 990322'), (12, 'yyyyMMddZ ***** 19990322+0100'), (5, 'yyyyMMddHHmmssSSS ***** 19990322204657111'), (34, 'HH:mm:ss.SSS ***** 20:46:57.111'), (27, 'dd/MM/yy ***** 22:03:99'), (1, 'yyyyMMdd ***** 19990322'), (21, "YYYY'W'wc ***** 1999W132"), (0, 'personalize ***** personalize'), (17, "yyyy-MM-dd'T'HH:mm:ss.SSS'Z' ***** 1999-03-22T05:06:07.000Z"), (30, "dd-MM-yyyy'T'HH:mm:ss.SSS ***** 22:03:1999'T'20:46:57.111"), (9, 'yy/MM/dd ***** 99/03/22'), (4, 'yyyyMMddHHmmss ***** 19990322204657'), (31, "dd-MM-yyyy'T'hh:mm:ss ***** 22:03:1999'T'08:46:57"), (11, 'yyyy-MM-dd ***** 1999-03-22'), (22, "YYYY-'W'w-c ***** 1999-W13-2"), (29, "dd-MM-yyyy'T'HH:mm:ss ***** 22:03:1999'T'20:46:57"), (32, "dd-MM-yyyy'T'hh:mm:ss.SSS ***** 22:03:1999'T'08:46:57.111"), (26, 'dd/MM/yyyy ***** 22/03/1999'), (36, 'hh:mm:ss.SSS ***** 08:46:57.111'), (18, "yyyy-MM-dd'T'HH:mm:ss.SSSXXX ***** 1999-03-22T05:06:07.000+01:00"), (8, 'yyyy/MM/dd ***** 1999/03/22'), (35, 'hh:mm:ss ***** 08:46:57'), (6, 'yyyyMMddhhmmss ***** 19990322084657'), (7, 'yyyyMMddhhmmssSSS ***** 19990322084657111'), (33, 'HH:mm:ss ***** 20:46:57'), (24, "yyyy-MM-dd'T'HH:mm:ssXXX'['VV']' ***** 1999-03-22T05:06:07+01:00[Europe/Paris]"), (20, 'yyyy-DDDXXX ***** 1999-081+01:00')], default=0, help_text='Select the format of your date/time string or type your own format in the field above if none feets with your column', verbose_name='time format')),
                ('dt_rule', models.CharField(blank=True, default='', help_text='Please, Specify the date/time format rule', max_length=100, null=True, verbose_name='datetime transformation rule')),
                ('bl_datetime', models.BooleanField(default=False, help_text='keep full date and time informations', verbose_name='full date and time')),
                ('bl_date', models.BooleanField(default=False, help_text='keep date informations', verbose_name='full date')),
                ('bl_time', models.BooleanField(default=False, help_text='keep time informations', verbose_name='full time')),
                ('bl_years', models.BooleanField(default=False, help_text='keep years', verbose_name='years')),
                ('bl_months', models.BooleanField(default=False, help_text='keep months', verbose_name='months')),
                ('bl_weeks', models.BooleanField(default=False, help_text='keep weeks', verbose_name='weeks')),
                ('bl_weekdays', models.BooleanField(default=False, help_text='keep weekdays', verbose_name='weekdays')),
                ('bl_days', models.BooleanField(default=False, help_text='keep days', verbose_name='days')),
                ('bl_hours', models.BooleanField(default=False, help_text='keep hours', verbose_name='hours')),
                ('bl_minutes', models.BooleanField(default=False, help_text='keep minutes', verbose_name='minutes')),
                ('bl_seconds', models.BooleanField(default=False, help_text='keep seconds', verbose_name='seconds')),
            ],
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'column', 'verbose_name_plural': 'columns'},
        ),
        migrations.AlterField(
            model_name='column',
            name='category',
            field=models.IntegerField(choices=[(0, 'keep'), (1, 'dummelies'), (2, 'frequencies'), (3, 'ordinals')], default=0, help_text='How would you manage category values ?<br>Category is a non numerical value that can not be computed (sum, mean,... )<br>it is often a text field like country or color...', verbose_name='managing categories'),
        ),
        migrations.AddField(
            model_name='timecolumn',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacollect.Column'),
        ),
    ]
