# Generated by Django 2.0.8 on 2019-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollect', '0007_auto_20190506_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='outliers',
            field=models.BooleanField(default=False, help_text='set a filter on values that are out of a standard range for this dataset', verbose_name='drop outliers'),
        ),
        migrations.AlterField(
            model_name='timecolumn',
            name='dt_format',
            field=models.IntegerField(choices=[(0, 'personalize ***** personalize'), (5, 'yyyyMMddHHmmssSSS ***** 19990322204657111'), (12, 'yyyyMMddZ ***** 19990322+0100'), (23, "yyyy-MM-dd'T'HH:mm:ss.SSSXXX'['VV']' ***** 1999-03-22T05:06:07.000+01:00[Europe/Paris]"), (28, 'dd-MM-yyyy ***** 22-03-1999'), (7, 'yyyyMMddhhmmssSSS ***** 19990322084657111'), (20, 'yyyy-DDDXXX ***** 1999-081+01:00'), (10, 'yyMMdd ***** 990322'), (21, "YYYY'W'wc ***** 1999W132"), (25, 'ddMMyyyy ***** 22031999'), (26, 'dd/MM/yyyy ***** 22/03/1999'), (34, 'HH:mm:ss.SSS ***** 20:46:57.111'), (29, "dd-MM-yyyy'T'HH:mm:ss ***** 22:03:1999'T'20:46:57"), (35, 'hh:mm:ss ***** 08:46:57'), (24, "yyyy-MM-dd'T'HH:mm:ssXXX'['VV']' ***** 1999-03-22T05:06:07+01:00[Europe/Paris]"), (33, 'HH:mm:ss ***** 20:46:57'), (9, 'yy/MM/dd ***** 99/03/22'), (27, 'dd/MM/yy ***** 22:03:99'), (6, 'yyyyMMddhhmmss ***** 19990322084657'), (3, 'yyyyMMddhhmm ***** 199903220846'), (22, "YYYY-'W'w-c ***** 1999-W13-2"), (4, 'yyyyMMddHHmmss ***** 19990322204657'), (32, "ddtimecolumn-MM-yyyy'T'hh:mm:ss.SSS ***** 22:03:1999'T'08:46:57.111"), (15, "yyyy-MM-dd'T'HH:mm:ss.SSS ***** 1999-03-22T05:06:07.000"), (17, "yyyy-MM-dd'T'HH:mm:ss.SSS'Z' ***** 1999-03-22T05:06:07.000Z"), (13, 'yyyy-MM-ddXXX ***** 1999-03-22+01:00'), (19, "yyyy-MM-dd'T'HH:mm:ssXXX ***** 1999-03-22T05:06:07+01:00"), (30, "dd-MM-yyyy'T'HH:mm:ss.SSS ***** 22:03:1999'T'20:46:57.111"), (1, 'yyyyMMdd ***** 19990322'), (18, "yyyy-MM-dd'T'HH:mm:ss.SSSXXX ***** 1999-03-22T05:06:07.000+01:00"), (2, 'yyyyMMddHHmm ***** 199903222046'), (31, "dd-MM-yyyy'T'hh:mm:ss ***** 22:03:1999'T'08:46:57"), (8, 'yyyy/MM/dd ***** 1999/03/22'), (36, 'hh:mm:ss.SSS ***** 08:46:57.111'), (11, 'yyyy-MM-dd ***** 1999-03-22'), (14, "yyyy-MM-dd'T'HH:mm:ss.SSS['VV'] ***** 1999-03-22T05:06:07.000[Europe/Paris]"), (16, "yyyy-MM-dd'T'HH:mm:ss ***** 1999-03-22T05:06:07")], default=0, help_text='Select the format of your date/time string or type your own format in the field above if none feets with your column', verbose_name='time format'),
        ),
    ]
