# Generated by Django 2.0.8 on 2019-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollect', '0008_auto_20190515_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecolumn',
            name='column',
        ),
        migrations.AlterField(
            model_name='column',
            name='alter_rule',
            field=models.CharField(blank=True, default='', help_text='Please, Specify the rule', max_length=255, null=True, verbose_name='field transformation rule'),
        ),
        migrations.AlterField(
            model_name='column',
            name='nan_rule',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='please specify a value'),
        ),
        migrations.DeleteModel(
            name='TimeColumn',
        ),
    ]
