# Generated by Django 2.0.8 on 2019-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey2019',
            old_name='analysis_frequency',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='autonomy',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='correlation',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='data_access',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='data_science',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='dependant',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='employee_activity',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='enterprise_activity_other',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='enterprise_classification',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='enterprise_classification_other',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='extraction',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='firm_size',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='reporting_style',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='reporting_tool',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='scientific',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='segmentation',
        ),
        migrations.AddField(
            model_name='survey2019',
            name='activity',
            field=models.IntegerField(choices=[(1, 'energy, electricity, gas, steam, water supply...'), (2, 'transportation, storage and logistic'), (3, 'IT/telecom'), (4, 'wholesale and retail trade, fashion, clothes, shoes'), (5, 'health and social work activities'), (6, 'bank, insurance or financial activities'), (7, 'industry and manufacturing'), (8, 'construction, building, real estate'), (9, 'public administration, government'), (10, 'research, science'), (11, 'information, media, communication, digital'), (12, 'cinema, arts and entertainment '), (13, 'education'), (14, 'legal, law'), (15, 'other service activities'), (16, 'sport, recreation, outdoor'), (17, 'hotel, accomodation, restaurant, food service activities'), (18, 'agriculture, forestry, fishing, environment'), (19, 'non governmental organisation'), (20, 'other')], default=0, verbose_name='company activity'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='activity_other',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name="specify the company's activity"),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='can_extract',
            field=models.BooleanField(default=False, verbose_name='extract the data of the reporting tool to make analysis in a spreadsheets tool'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='classif',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'not so much '), (2, 'yes '), (3, 'Yes very much')], default=1, verbose_name='classification, automated categories assignment'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='correl',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'not so much '), (2, 'yes '), (3, 'Yes very much')], default=1, verbose_name='finding correlation among your data, causality or links between events'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='has_data',
            field=models.BooleanField(default=True, unique=True, verbose_name='holding data'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='has_mathematic',
            field=models.BooleanField(default=False, verbose_name='do you have large mathematic or statistic knowledge'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='has_scientist',
            field=models.BooleanField(default=False, verbose_name='do you have a data scientist or data analyst easily approachable in your working environment'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='is_autonomous',
            field=models.BooleanField(default=False, verbose_name='autonomous for building reports'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='is_dependant',
            field=models.BooleanField(default=False, verbose_name='feel highly dependant from other department (it, partner company...)'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='pict',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'not so much '), (2, 'yes '), (3, 'Yes very much')], default=1, verbose_name='picture categorization'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='predict',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'not so much '), (2, 'yes '), (3, 'Yes very much')], default=1, verbose_name='predicting results'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='revenue',
            field=models.IntegerField(blank=True, choices=[(0, 'Rather not say'), (1, 'less than €1 Million'), (10, '€1 Million to 10€ Million'), (100, '€10 Million to 100€ Million'), (500, '€100 Million to 500€ Million'), (1000, '€500 Million to 1€ Billion'), (5000, 'over 1€ Billion')], default=10, verbose_name='firm Size'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='role',
            field=models.IntegerField(choices=[(1, 'financial'), (2, 'accountant'), (3, 'IT/telecom'), (4, 'marketing communication'), (5, 'sales'), (6, 'storage, logistic, supply-chain, transportation'), (7, 'human ressources'), (8, 'consulting, audit'), (9, 'research, science, lab'), (10, 'health, medical'), (11, 'journalism'), (12, 'management, upper management'), (13, 'education'), (14, 'legal'), (15, 'buying, sourcing'), (16, 'technical, production'), (17, 'administration'), (18, 'support services'), (19, 'liberal, partner, self employment'), (20, 'other')], default=0, max_length=2, verbose_name='employee role'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='role_other',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='specify your occupation'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='segment',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'not so much '), (2, 'yes '), (3, 'Yes very much')], default=1, verbose_name='segmentation, building relevant groups among your data'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='text',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'not so much '), (2, 'yes '), (3, 'Yes very much')], default=1, verbose_name='text categorization'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='tool',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, 'none, pocket calculator'), (1, 'Spreadsheet, Microsoft Excel, Google Sheets, Open Office Calc'), (2, 'Business Intelligence Desktop tools, Tableau, Qlik Sense, Sisense, Looker...'), (3, 'Business Intelligence enterprise reporting tools, SAP Business Objects, IBM Cognos, Microsoft Analysis Services/Power BI '), (4, 'mainframe reports'), (5, 'developper tools, Python, Java, C#...')], default=1, verbose_name='reporting tool'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='visualization',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, 'raw listings'), (2, 'columns tables'), (3, 'pivot tables'), (4, 'Olap hypercubes'), (5, 'graphs, curves or charts')], default=30, verbose_name='visualization style of the reporting'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='anomaly',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'not so much '), (2, 'yes '), (3, 'Yes very much')], default=1, verbose_name='anomaly detection ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='columns',
            field=models.IntegerField(default=5, verbose_name='average number of columns/indicators in a report'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='lines',
            field=models.IntegerField(default=50, verbose_name='average number of lines in a reports'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='reports',
            field=models.IntegerField(default=1, verbose_name='average number of distinct reports are you browsing'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='test1',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, '1.'), (2, '2.'), (3, '2.')], default=1, verbose_name='test1'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='test2',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, '1.'), (2, '2.'), (3, '2.')], default=1, verbose_name='test2'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='test3',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, '1.'), (2, '2.'), (3, '2.')], default=1, verbose_name='test3'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='test4',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, '1.'), (2, '2.'), (3, '2.')], default=1, verbose_name='test4'),
        ),
    ]
