# Generated by Django 2.0.8 on 2019-02-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190206_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey2019',
            name='role',
            field=models.IntegerField(choices=[(1, 'financial'), (2, 'accountant'), (3, 'IT/telecom'), (4, 'marketing communication'), (5, 'sales'), (6, 'storage, logistic, supply-chain, transportation'), (7, 'human ressources'), (8, 'consulting, audit'), (9, 'research, science, lab'), (10, 'health, medical'), (11, 'journalism'), (12, 'management, upper management'), (13, 'education'), (14, 'legal'), (15, 'buying, sourcing'), (16, 'technical, production'), (17, 'administration'), (18, 'support services'), (19, 'liberal, partner, self employment'), (20, 'other')], default=0, verbose_name='employee role'),
        ),
    ]
