# Generated by Django 2.0.8 on 2019-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190208_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey2019',
            name='has_data',
            field=models.BooleanField(default=True, verbose_name='holding data'),
        ),
    ]
