# Generated by Django 2.0.8 on 2019-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20190208_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey2019',
            name='uid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='lines',
            field=models.IntegerField(default=0, verbose_name='average number of lines in a reports'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='reports',
            field=models.IntegerField(default=0, verbose_name='average number of distinct reports are you browsing'),
        ),
    ]
