# Generated by Django 2.0.8 on 2019-02-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20190211_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey2019',
            name='records',
            field=models.IntegerField(default=0, verbose_name='largest size of datasets on which reports rely on'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='email',
            field=models.EmailField(help_text="We'll never share your email with anyone else.", max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='tool',
            field=models.IntegerField(choices=[(0, ''), (1, "I don't know"), (2, 'none, a pocket calculator or pencil, rubber and paper...'), (3, 'Spreadsheet, Microsoft Excel, Google Sheets, Open Office Calc'), (4, 'Business Intelligence Desktop tools, Tableau, Qlik Sense, Sisense, Looker...'), (5, 'Business Intelligence enterprise reporting tools, SAP Business Objects, IBM Cognos, Microsoft Analysis Services/Power BI '), (6, 'IT specific reports'), (7, 'AI analysis, IBM Watson, Microsoft Azur Machine Learning...'), (7, 'developper tools, Python, Java, C#...'), (9, 'none of this...')], default=0, verbose_name='reporting tool'),
        ),
    ]
