# Generated by Django 2.0.8 on 2019-02-12 12:07

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('survey', '0011_auto_20190212_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey2019',
            name='keys',
        ),
        migrations.AddField(
            model_name='survey2019',
            name='company_description',
            field=models.TextField(blank=True, null=True, verbose_name='could you describe an IA use for your professional needs ?'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='company_keys',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_initial=True, autocomplete_view='tag:tag_subject_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='CRM, HR, IT, business, correlation, customers, learning, legal, production, retail, retail/sales, retail/stocks', max_count=15, related_name='company', to='tag.TagSubject', tree=True),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='issues_description',
            field=models.TextField(blank=True, null=True, verbose_name='do you imagine some issues analysing data with IA tools ?'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='private_activity',
            field=models.IntegerField(choices=[(0, ''), (1, 'sport'), (2, 'somehow scientific'), (3, 'managing an association'), (4, 'personal finance'), (5, 'pictures'), (6, 'social media'), (7, 'technologic, engine, personal IT'), (99, 'other..')], default=0, verbose_name='private activities'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='private_description',
            field=models.TextField(blank=True, null=True, verbose_name='could you describe an IA use for your private activities ?'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='private_keys',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_initial=True, autocomplete_view='tag:tag_subject_autocomplete', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='CRM, HR, IT, business, correlation, customers, learning, legal, production, retail, retail/sales, retail/stocks', max_count=15, related_name='private', to='tag.TagSubject', tree=True),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='private_tool',
            field=models.IntegerField(choices=[(0, ''), (2, 'none, a pocket calculator or pencil, rubber and paper...'), (3, 'Spreadsheet, Microsoft Excel, Google Sheets, Open Office Calc'), (6, "Web's software as a service solution"), (99, 'others...')], default=0, verbose_name='reporting tool for private activities'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='tool',
            field=models.IntegerField(choices=[(0, ''), (1, "I don't know"), (2, 'none, a pocket calculator or pencil, rubber and paper...'), (3, 'Spreadsheet, Microsoft Excel, Google Sheets, Open Office Calc'), (4, 'Business Intelligence Desktop tools, Tableau, Qlik Sense, Sisense, Looker...'), (5, 'Business Intelligence enterprise reporting tools, SAP Business Objects, IBM Cognos, Microsoft Analysis Services/Power BI '), (6, "Web's software as a service solution"), (7, 'IT specific reports'), (8, 'AI analysis, IBM Watson, Microsoft Azur Machine Learning...'), (9, 'developper tools, Python, Java, C#...'), (10, 'none of this...')], default=0, verbose_name='reporting tool'),
        ),
    ]
