# Generated by Django 2.0.8 on 2019-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20190212_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey2019',
            name='has_opendata',
            field=models.BooleanField(default=False, help_text='Data freely provided by government or other organisations like traffic, meteo, train scheedules...', verbose_name="are you dealing with 'open data' ?"),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='activity',
            field=models.IntegerField(choices=[(0, ''), (1, 'wholesale distribution and retail trade'), (2, 'IT, digital, software, internet and telecom'), (3, 'bank, insurance or financial activities'), (4, 'industry and manufacturing'), (5, 'transportation, storage and logistic'), (6, 'construction, building, real estate'), (7, 'computers and electronics'), (8, 'research, science, environment'), (9, 'energy, electricity, gas, steam, water supply...'), (10, 'agriculture, forestry, fishing, mining'), (11, 'legal, law'), (12, 'professional services'), (13, 'information, media, communication'), (14, 'cinema, arts, entertainment and gaming'), (15, 'sport, recreation, outdoor'), (16, 'travel, hospitality, accomodation, restaurant, food activities'), (17, 'healthcare and social work activities'), (18, 'education'), (19, 'public administration, government'), (20, 'non-profit organisation'), (99, 'other...')], default=0, help_text='Select the main sector of the company/organization you are working in...', verbose_name='company activity'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='activity_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Please, specify the company's activity"),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='email',
            field=models.EmailField(help_text="We'll never share your email with anyone else...", max_length=254, null=True, verbose_name='please, type your email address below if you wish to be informed of our activities, '),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='has_data',
            field=models.BooleanField(default=True, help_text='Check if your department is holding data (sales, logistic, clients, studies)', verbose_name='Are you dealing with data ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='revenue',
            field=models.IntegerField(choices=[(0, ''), (1, 'less than €1 Million'), (10, '€1 Million to €10 Million'), (100, '€10 Million to €100 Million'), (500, '€100 Million to €500 Million'), (1000, '€500 Million to €1 Billion'), (5000, 'over 1€ Billion')], default=0, help_text='Select the average annual revenue of your company. Leave empty if not allowed', verbose_name='company annual revenue'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='role',
            field=models.IntegerField(choices=[(0, ''), (1, 'liberal, partner, self employed'), (2, 'financial, accounting'), (3, 'IT/telecom'), (4, 'marketing, communication'), (5, 'sales'), (6, 'storage, logistic, supply-chain, transportation'), (7, 'human ressources'), (8, 'consultant, advisor'), (9, 'research, science academic'), (10, 'health, medical'), (11, 'journalist, media analyst'), (12, 'business executive, management, upper management'), (13, 'education'), (14, 'legal'), (15, 'buying, sourcing'), (16, 'technical, production'), (17, 'administration'), (18, 'developer, engineer'), (19, 'support services'), (20, 'entrepreneur'), (21, 'student'), (99, 'other...')], default=0, help_text='What is your occupation; the department in which you work ?', verbose_name='employee role'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='role_other',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Please, specify your occupation'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='type',
            field=models.IntegerField(choices=[(0, ''), (1, 'self employed'), (2, 'local administration'), (3, 'government'), (4, 'education'), (5, 'enterprise'), (6, 'non-profit, non governmental organisation'), (7, 'small or medium business'), (8, 'start-up'), (99, 'other...')], default=0, help_text='Select the type of company which is closer from the one you are working in...', verbose_name='company type'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='type_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Please, Specify the company's type"),
        ),
    ]
