# Generated by Django 2.0.8 on 2019-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20190214_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey2019',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='test3',
        ),
        migrations.RemoveField(
            model_name='survey2019',
            name='test4',
        ),
        migrations.AddField(
            model_name='survey2019',
            name='ai',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, "it's science fiction only"), (2, "it's a matter of huge company, self driving cars and big data"), (3, 'I would like to know how it can improve my business'), (4, "I'm already engaged'")], default=0, help_text='Wether you know who is HAL or not; What inspires you the concept of "artificial intelligence" ?', null=True, verbose_name='"Artificial intelligence" ?'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='ml',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know and I really don't care"), (1, 'Somehow a technical thing with computers and machines'), (2, 'It is related to education, like MOOCs, but machine are teaching'), (3, 'Obviously making prediction on some features by "training" a model with data')], default=0, help_text='have you already heard of "machine learning" ?', null=True, verbose_name=' "Machine learning" ?'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='pred',
            field=models.IntegerField(blank=True, choices=[(0, "I don't need that"), (1, 'I already can estimate outputs by myself'), (2, "I won't be confident on prediction given by a machine"), (3, 'I would like to try on my own data')], default=1, help_text='Do you believe in prediction given by some algorythms ?', null=True, verbose_name='"Predictions" ?'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='smart',
            field=models.IntegerField(blank=True, choices=[(0, "I don't want to know"), (1, "it's like big data but comming from something smart"), (2, "In my systems, data are not smart, it's only raw data"), (3, 'Less data but more relevant to have significant outputs and make decision')], default=1, help_text='is "smart data" concept relevant to you ?', null=True, verbose_name='"Smart data" ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='has_mathematic',
            field=models.BooleanField(default=False, help_text='Do you have some knowledge of mathematics or statistics that allow you to make advanced analysis of your data ?<br>You master regression analysis (linear, polynomial or logistic) and many other heuristics and you know how to use them...', verbose_name='Do you have some mathematical background ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='has_scientist',
            field=models.BooleanField(default=False, help_text='Do you have any data scientist or any dedicated team, easily approachable, in your working environment, with whom any Analysis question will have its answer in a few hours ? ', verbose_name='Are you close from data analysts ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='is_analyst',
            field=models.BooleanField(default=False, help_text='Do you often dive in your data to have a better understanding of underlying issues, rather than tracking the evolution of variables thru time ?', verbose_name='Do you analyze your data yourself ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='is_dependant',
            field=models.BooleanField(default=False, help_text='Check if you do not feel highly dependant from others to access new sets of data.<br>If you do not rely on someone else&#39;s work and need to make a request to another department (e.g. IT) , consultants or a partner company and wait for a while before getting datasets or reports ', verbose_name='Are you independant ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='private_activity',
            field=models.IntegerField(choices=[(0, ''), (1, 'sport'), (2, 'somehow scientific'), (3, 'managing an association'), (4, 'personal finance'), (5, 'pictures'), (6, 'cinema, music, some arts'), (7, 'social media'), (8, 'games, e-sport'), (9, 'bet, gambling, sport statistics'), (10, 'technologic, engine, personal IT'), (99, 'other..')], default=0, help_text='Whether it yield data you could analyze or not, are you involved in some private activities ?  <br>From managing an association to training hard in some sports is there a specific activity in which you spend your free time ?', verbose_name='Engaging in private activities ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='private_tool',
            field=models.IntegerField(choices=[(0, ''), (1, 'none, a pocket calculator or pencil, rubber and paper...'), (2, 'Spreadsheet, Microsoft Excel, Google Sheets, Open Office Calc'), (3, "Web's software as a service solution"), (4, 'some Apps (Strava, Runkeeper, Imdb, BetClic'), (99, 'others...')], default=0, help_text='Is there any tool you use for that private activity ?', verbose_name='Analyzing private activities ?'),
        ),
    ]
