# Generated by Django 2.0.8 on 2019-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190215_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey2019',
            name='browser',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='client browser'),
        ),
        migrations.AddField(
            model_name='survey2019',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP address'),
        ),
    ]
