# Generated by Django 2.0.8 on 2019-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20190221_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey2019',
            name='activity_other',
            field=models.CharField(blank=True, help_text="Could you, please, specify  your company's activity in the text field below", max_length=50, null=True, verbose_name='specify activity'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='ai',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know"), (1, "it's science fiction only"), (2, "it's a matter of huge company, self driving cars and big data"), (3, 'I would like to know how it can improve my business'), (4, "I'm already engaged'")], default=0, help_text='Wether you know who is HAL or not; What inspires you the concept of "artificial intelligence" ?', null=True, verbose_name='Artificial intelligence ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='can_extract',
            field=models.BooleanField(default=False, help_text='Are you sometimes extracting data out of the reporting tool you are using ?<br>Check &#39;yes&#39; if you use to export raw data out of the reporting tool to make analysis in a spreadsheets tool.', verbose_name='data extraction'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='has_data',
            field=models.BooleanField(default=True, help_text="Check 'yes' if your department is holding data (sales, logistic, clients, products details, technical data...)", verbose_name='Are you dealing with data ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='has_mathematic',
            field=models.BooleanField(default=False, help_text='Do you have any mathematical backgrounds or some knowledge of mathematics and statistics that allow you to make advanced analysis of your data ?<br>You master regression analysis (linear, polynomial or logistic) and many other heuristics and you know how to use them...', verbose_name='any mathematical background ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='has_scientist',
            field=models.BooleanField(default=False, help_text='Do you have any data scientists or any dedicated team, easily approachable, in your working environment, with whom any Analysis question will have its answer in a few hours ? ', verbose_name='data analysts around you?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='is_dependant',
            field=models.BooleanField(default=False, help_text='Check &#39;yes&#39; if you do not feel highly dependant from others to access new sets of data.<br>If you do not rely on someone else&#39;s work and need to make a request to another department (e.g. IT) , consultants or a partner company and wait for a while before getting datasets or reports.', verbose_name='Are you independant ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='ml',
            field=models.IntegerField(blank=True, choices=[(0, "I don't know and I really don't care"), (1, 'Somehow a technical thing with computers and machines'), (2, 'It is related to education, like MOOCs, but machine are teaching'), (3, 'Obviously making prediction on some features by "training" a model with data')], default=0, help_text='have you already heard of "machine learning" ?', null=True, verbose_name='Machine learning ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='pred',
            field=models.IntegerField(blank=True, choices=[(0, "I don't need that"), (1, 'I already can estimate outputs by myself'), (2, "I won't be confident on prediction given by a machine"), (3, 'I would like to try on my own data')], default=1, help_text='Do you believe in prediction given by some algorithms ?', null=True, verbose_name='Predictions ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='private_activity',
            field=models.IntegerField(choices=[(0, ''), (1, 'sport'), (2, 'somehow scientific'), (3, 'managing an association'), (4, 'personal finance'), (5, 'pictures'), (6, 'cinema, music, some arts'), (7, 'social media'), (8, 'games, e-sport'), (9, 'bet, gambling, sport statistics'), (10, 'technologic, engine, personal IT'), (99, 'other..')], default=0, help_text='Whether it yield data you could analyze or not, are you involved in some private activities ?  From managing an association to training hard in some sports is there a specific activity in which you spend your free time ?', verbose_name='Engaging in private activities ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='records',
            field=models.IntegerField(choices=[(0, ''), (1, 'less than 1000'), (2, '1000 to 9,999 (thousand)'), (3, '10,000 to 99,999'), (4, '100,000 to 1 Million'), (5, '1 Million to 500 Million'), (6, 'over 500 Million')], default=0, help_text='What is the size of datasets on which reports rely on ?<br>e.g. a report that display informations over three weeks in 200 stores with an average of 50 sales a day,<br><em> ...the number of records will be 50 x 200 x 7 x 3 = 210,000</em>', verbose_name='Average number of records'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='revenue',
            field=models.IntegerField(choices=[(0, ''), (1, 'less than €1 Million'), (2, '€1 Million to €10 Million'), (3, '€10 Million to €100 Million'), (4, '€100 Million to €500 Million'), (5, '€500 Million to €1 Billion'), (6, 'over 1€ Billion')], default=0, help_text='Select the average annual revenue of your company. Leave empty if not allowed.', verbose_name='company annual revenue'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='role_other',
            field=models.CharField(blank=True, default='', help_text='Could you, please, specify your occupation in the text field below.', max_length=50, null=True, verbose_name='specify occupation'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='smart',
            field=models.IntegerField(blank=True, choices=[(0, "I don't want to know"), (1, "it's like big data but comming from something smart"), (2, "In my systems, data are not smart, it's only raw data"), (3, 'Less data but more relevant to have significant outputs and make decision')], default=1, help_text='is "smart data" concept relevant to you ?', null=True, verbose_name='Smart data ?'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='type_other',
            field=models.CharField(blank=True, help_text="Could you, please, specify your company's type in the text field below", max_length=50, null=True, verbose_name='specify type'),
        ),
        migrations.AlterField(
            model_name='survey2019',
            name='visualization',
            field=models.IntegerField(choices=[(0, ''), (1, "I don't know"), (2, 'raw listings'), (3, 'columns tables'), (4, 'pivot tables'), (5, 'Olap hypercubes'), (6, 'graphs, curves or charts')], default=0, help_text='How are you mainly visualizing your data ?<br>What style of reporting are you dealing with ?', verbose_name='reporting style'),
        ),
    ]
